version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: app
    restart: unless-stopped
    #tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network
#  node:
#      image: node:18
#      container_name: node
#      working_dir: /var/www
#      depends_on:
#          - 'app'
  #MySQL Service
#  db:
#    image: mysql:8.0
#    container_name: db
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - ./mysql/:/var/lib/pos
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
#    networks:
#      - app-network
  worker:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: worker
      restart: always
      command: php artisan solar:listen
      working_dir: /var/www
      volumes:
          - ./storage/logs:/var/www/storage/logs   # optional, for log persistence
      environment:
          - SOLAR_DEVICE_IP=${SOLAR_DEVICE_IP}
          - SOLAR_PASSWORD=${SOLAR_PASSWORD}
          - DB_CONNECTION=${DB_CONNECTION}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - DB_DATABASE=${DB_DATABASE}
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
      networks:
          - app-network
      depends_on:
          - app
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
