FROM php:8.3-fpm

WORKDIR /var/www

COPY composer.json composer.lock ./
COPY artisan ./
COPY app/ app/
COPY bootstrap/ bootstrap/
COPY config/ config/
COPY database/ database/
COPY public/ public/
COPY resources/ resources/
COPY routes/ routes/
COPY storage/ storage/
COPY vendor/ vendor/

CMD ["php", "artisan", "solar:listen"]
